import type { Metadata } from 'next'
import { Inter, Ubuntu } from 'next/font/google'

import './globals.css'
import { ClerkProvider, RedirectToSignIn, SignedIn, SignedOut } from '@clerk/nextjs'
import { MyContextProvider, useMyContext } from '@/components/Context'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })
const ubuntu = Ubuntu({weight:"300",subsets: ['latin']})

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
//   openGraph: {
//     images:[{
//       url:'/thumbnail.png',
//       width:800,
//       height:600,
//     }]
//   }
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (

    <ClerkProvider>
      <html lang="en">
        <Head>
          <meta property='og:title' content='My page title' key='title' />
          <meta property='og:description' content='My page description' />
          <meta property='og:image' content='/thumbnail.png' />
        </Head>
        <body className={`${ubuntu.className}`}>
          <SignedIn>
            {children}
          </SignedIn>
          <SignedOut>
            <RedirectToSignIn />
          </SignedOut>
        </body>
      </html>
    </ClerkProvider> 

  )
}

